### ISSUE TITLE
Automate FB Access Token Renewal

### ISSUE THREAD

**Issue by aero31aero** [aero31aero/shoutboxx-calendar#6]
Create a script which takes an existing token(and other details, if you need) and returns a new token. If it works, it'll be integrated in the main code.

**Comment by ghost** [comment]
Yeah, small issue. Just as we thought, we can't pragmatically generate a new token. But we can create a facebook app for ourselves using which we can generate a permanent token. Should I go ahead?

**Comment by hit023** [comment]
Doesn't token here mean token for the individual accessing the graph api?

**Comment by aero31aero** [comment]
@hit023 Go ahead with app creation then if that's the way to solve our issue.

**Comment by aero31aero** [comment]
@aero31aero If we have access token, it doesn't care who uses the token as long as the token is valid. And yes, a token is generated by an app for a user. So far we've been using the app "graph api explorer" on our user accounts.
